id = "template-toolkit"
name = "Template Toolkit"
version = "0.1.0"
schema_version = 1
authors = ["Jan Limpens"]
description = "Template Toolkit (TT) syntax highlighting for Zed. Supports .tt, .tt2, .ttml files with HTML + TT directive highlighting."
repository = "https://github.com/janlimpens/zed-ttk"
themes = []
icon_themes = []
languages = ["languages/ttk"]
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.ttk]
repository = "https://github.com/janlimpens/tree-sitter-ttk"
commit = "5a7526a"
