name = "Template Toolkit"
grammar = "ttk"
path_suffixes = ["tt", "tt2", "ttml"]
block_comment = ["[%# ", " %]"]
line_comments = ["# "]
autoclose_before = ">})\"'"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = true, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = true, newline = true, not_in = ["comment", "string"] },
    { start = "<", end = ">", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "!--", end = " --", close = true, newline = true },
    { start = "[%", end = "%]", close = true, newline = true, not_in = ["comment"] },
]
wrap_characters = { start_prefix = "<", start_suffix = ">", end_prefix = "</", end_suffix = ">" }
tab_size = 2
